# Generated by Django 6.0.3 on 2026-04-08 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=64)),
                ('port', models.IntegerField(default=80)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('track_id', models.CharField(default='1', max_length=16)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MotionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='', max_length=100)),
                ('channel', models.CharField(default='1', max_length=16)),
                ('event_type', models.CharField(choices=[('motion_start', 'Motion Start'), ('motion_stop', 'Motion Stop')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api_app.camerasite')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
