# Generated by Django 4.2.7 on 2026-04-13 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_source', models.CharField(choices=[('CAMERA', 'Camera Motion'), ('PIR_1', 'PIR Sensor 1'), ('PIR_2', 'PIR Sensor 2'), ('PIR_3', 'PIR Sensor 3'), ('PIR_4', 'PIR Sensor 4')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api_app.camerasite')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
